### ISSUE TITLE
梅斯需求：列表页面操作 、序号、选择列，可以通过属性来控制是否显示整列（需讨论）

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-widgets#221]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/211517325-eb34bced-fb4e-4730-b5cd-05d77a38f452.png">

**Comment by hotlong** [comment]
相关任务 https://github.com/steedos/steedos-widgets/issues/301
