### ISSUE TITLE
列表页定义的字段宽度未生效，且无法拖动

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-widgets#305]
"@steedos/service-enterprise": "2.4.0-beta.36"

![image](https://user-images.githubusercontent.com/6194896/222676799-011a8d7a-be82-47b6-974d-b08951ea14b6.png)

**Comment by yinlianghui** [comment]
先实现“切换列换行的属性” ：https://github.com/steedos/steedos-widgets/issues/372
