### ISSUE TITLE
使用最新版本后，页面内容都变成了人员。还有标准对象页面新建按钮都没了

### ISSUE THREAD

**Issue by xiaokedou5951** [steedos/steedos-widgets#316]
![企业微信截图_16795413632029](https://user-images.githubusercontent.com/61674418/227095817-26a329ed-d06d-4c22-a733-be788ed12b8e.png)

**Comment by hotlong** [comment]
试试项目升级到2.4.5

**Comment by xiaokedou5951** [comment]
使用最新版本包含了：项目也升到了2.4.5

**Comment by hotlong** [comment]
参考项目模版中的 .env 

https://gitlab.steedos.cn/steedos/steedos-project-template

**Comment by hotlong** [comment]
我知道了，你运行的nextjs项目

**Comment by hotlong** [comment]
@yinlianghui 确认一下

**Comment by hotlong** [comment]
你测试的问题，是运行这个项目下的apps/experience吗？

**Comment by yinlianghui** [comment]
无法重现
