### ISSUE TITLE
在带树形结构的数据中，相关里新建弹框不会把有3层级节点的数据给回显出来，只有没节点的数据才能正常回显

### ISSUE THREAD

**Issue by 774649283** [steedos/steedos-widgets#319]
![企业微信截图_16795509488771](https://user-images.githubusercontent.com/17950491/227131691-97c42b98-f4ac-45ef-a2e9-28c37394fc5f.png)
![企业微信截图_16795512055663](https://user-images.githubusercontent.com/17950491/227131697-e1f7cef8-9e05-40c5-a298-4997ecc7a59d.png)

**Comment by yinlianghui** [comment]
华炎魔方2.5引用的是amis 2.9，已经无法重现此问题了
