### ISSUE TITLE
对象表格/对象表单组件，默认当前对象时，显示/排除的字段设置时选择不到字段

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-widgets#371]
<img width="1605" alt="image" src="https://user-images.githubusercontent.com/26241897/226780864-33823b80-36cf-4a39-8108-8c5eede9e8dc.png">

<img width="1580" alt="image" src="https://user-images.githubusercontent.com/26241897/226781097-bd31201d-7516-4191-8ddd-2b10ad3e268a.png">

**Comment by Flyingliao** [comment]
最新系统是正常的 2.5.15-beta.12。 
<img width="803" alt="image" src="https://github.com/steedos/steedos-widgets/assets/41402189/9e6e73cf-c889-4a73-b119-ed2dd49998e4">
