### ISSUE TITLE
[Feature]: 在lookup弹出窗口中新建记录后，直接选中此记录

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-widgets#378]
### Summary 摘要

目前在合同等对象中选择业务伙伴，弹出业务伙伴选择页面，点击新建按钮，新建业务伙伴后，并未直接选中此业务伙伴，需要再次筛选并选择，需要新建后直接选中此业务伙伴

### Why should this be worked on? 此需求的应用场景？

新建合同，项目时无此业务伙伴，需要新建业务伙伴

**Comment by Flyingliao** [comment]
技术层面分析：
1、新建的记录能从返回值中获取 ID 。 如果字段配置了reference_to_field, 获取记录的ID就不够。需要想办法获取 reference_to_field 属性值的值。
2、lookup.js中能获取field.name, field.multiple, field.reference_to, field.reference_to_field。
3、从上层数据域 event.data._master中能获取到 主记录 。
4、需要想办法获取到主记录表单的组件ID。
