### ISSUE TITLE
[Bug]: 日历组件时间异常

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-widgets#382]
### Description

![image](https://user-images.githubusercontent.com/6194462/231086664-c9b7ec90-78b2-4e37-a4fc-c6d93f44588d.png)

### Steps To Reproduce 重现步骤

1 进入到events对象列表
2 切换到日历视图
3 按住鼠标选择时间后, 弹出的窗口中时间和选中的时间不一致. 始终是 16-17点

### Version 版本

1.1

**Comment by hotlong** [comment]
重复 https://github.com/steedos/steedos-widgets/issues/369
