### ISSUE TITLE
[Bug]: 列表视图展示不完整

### ISSUE THREAD

**Issue by lijunjun2270249873** [steedos/steedos-widgets#392]
### Description

![Snipaste_2023-04-17_15-33-27](https://user-images.githubusercontent.com/109123143/232416240-ded46837-0b4c-4acb-867e-2afde26bd28e.png)

### Steps To Reproduce 重现步骤

![Snipaste_2023-04-17_15-33-27](https://user-images.githubusercontent.com/109123143/232416253-fb0f845b-e789-4959-9d22-080e0893d847.png)

### Version 版本

2.4.5

**Comment by yinlianghui** [comment]
重复 https://github.com/steedos/steedos-platform/issues/4757
