### ISSUE TITLE
[Bug]: 日程对象的日历视图中点击任意的日程，打开的记录详情弹框未显示具体内容，并报错

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-widgets#405]
### Description

![image](https://user-images.githubusercontent.com/127007861/233822797-9be6838c-25a2-4c4b-be29-54334ede881a.png)

### Steps To Reproduce 重现步骤

1.进入event对象的日历视图
2.新建一个日程记录
3.点击日程记录

### Version 版本

1.2

**Comment by tujiajun** [comment]
弹框打开的记录详情页已修复，但是之后的编辑按钮有新报错

**Comment by baozhoutao** [comment]
![image](https://user-images.githubusercontent.com/6194462/236097130-0c46624c-ebfd-47f1-8b49-dd6d65c28a8d.png)

未重现, 应被其他提交修复
