### ISSUE TITLE
[Bug]: 手机端列表视图不应该把底部的加载更多按钮固定在底部应该显示在滚动条内容里面

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-widgets#424]
### Description

出现这个问题的原因应该是PC下底部翻页固定在底部了，区别下手机端，手机上不要固定crud的footer应该就可以了。
![image](https://user-images.githubusercontent.com/6219465/236595549-9aa01802-a5e5-4137-95aa-6340ca2b497f.png)

### Steps To Reproduce 重现步骤

手机app进入某个对象列表，当列表数据比较多时，可以看到底部有一个独立的空白区域，当数据超过翻页数量的时候会也会显示加载更多按钮，问题是这个底部区域没有显示在滚动条内容一起，而是独立出来了。

### Version 版本

1.2.x

**Comment by Flyingliao** [comment]
底部“加载更多”按钮原始状态是 当记录全部加载完成后此按钮 不可点击。
![image](https://github.com/steedos/steedos-widgets/assets/41402189/c69ac0c3-3cef-441c-bac3-2e4a0952fe25)

现在的状态是 当不可点击 时，通过css设置 display:none 。但是由于按钮的上三层标签元素有各自的高度样式，导致目前加载完毕后会出现空白部分。

建议：
1、撤掉对“加载更多”按钮的样式设置。
2、取消“加载更多”按钮，采用滚动加载更多记录。【需要重新讨论思考方案】
