### ISSUE TITLE
[Bug]: 列表视图选择视图后, 视图选择器未自动关闭.

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-widgets#429]
### Description

![image](https://user-images.githubusercontent.com/6194462/237008777-5ef0690a-29e9-4aeb-acfc-7ba39b72f737.png)

### Steps To Reproduce 重现步骤

1 进入对象列表
2 切换视图

### Version 版本

1.2

**Comment by Flyingliao** [comment]
重复：https://github.com/steedos/steedos-platform/issues/4954
