### ISSUE TITLE
[Feature]: 将记录详情页相关子表按钮统一改为点击后弹出底部操作弹框

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-widgets#436]
### Summary 摘要

![image](https://github.com/steedos/steedos-widgets/assets/127007861/1d0fd8d2-a2b9-4cd8-a42e-f6380996fd4e)
![image](https://github.com/steedos/steedos-widgets/assets/127007861/29fbc6bd-9c4a-4305-8d78-5ef694d80dca)

### Why should this be worked on? 此需求的应用场景？

手机端操作按钮过多

**Comment by xxmm7758** [comment]
https://xmrth.cc/auth/register?code=W65D
