### ISSUE TITLE
[Bug]: 列表搜索栏点开后顶部出现白色背影色以及底部翻页也应该加一条线分隔列表内容

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-widgets#441]
### Description

![image](https://github.com/steedos/steedos-widgets/assets/6219465/0d1850c7-fee2-47b5-a564-c037e887612b)

### Steps To Reproduce 重现步骤

进入对象列表页面就能看到此问题

### Version 版本

1.2.x

**Comment by Flyingliao** [comment]
[crud底部工具栏pc端添加下外边距，手机端不添加下外边距](https://github.com/steedos/steedos-platform/commit/ec0e4a692409f32584f5fe54a477d353d0b0e5c9)
