### ISSUE TITLE
[Bug]:  列表视图上的搜索功能会导致页面异常.

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-widgets#458]
### Description

![image](https://github.com/steedos/steedos-widgets/assets/6194462/1f0bd756-9936-47c6-bbf3-036a624fb2b2)

### Steps To Reproduce 重现步骤

1 打开申请单列表视图
2 点击放大镜图标
3 选择流程多个,选择越多,页面越乱.

### Version 版本

1.2

**Comment by Flyingliao** [comment]
搜索模式已被修改，可以关闭该issue了
