### ISSUE TITLE
[Feature]: 列表视图支持批量编辑多行中的某个字段值

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-widgets#463]
#### sf效果：
<img width="1020" alt="image" src="https://github.com/steedos/steedos-widgets/assets/6219465/926e1308-55f8-4c2d-8cff-ac55a44fc983">

#### amis效果：
<img width="845" alt="image" src="https://github.com/steedos/steedos-widgets/assets/6219465/58733d7d-9a7f-4279-a141-9d62781eb0b9">

### Why should this be worked on? 此需求的应用场景？

快速编辑列表上多行的某个字段值。

**Comment by tujiajun** [comment]
context.context.parent.getComponents()[1].props.store.rows[0].locals
context.context.parent.getComponents()[1].props.store.rows[0].reset()
context.context.parent.getComponents()[1].props.store.rows[0].data
考虑从这几个函数中实现

**Comment by tujiajun** [comment]
当前考虑方案：
1.通过更新列表数据，修改各行的_display，以实现数据的回显
![image](https://github.com/steedos/steedos-widgets/assets/127007861/9cb0e8e5-0a03-4471-9390-d23b309b788e)
2.通过行记录字段赋值，修改每行需要提交的数据并触发quickedit的接口
![image](https://github.com/steedos/steedos-widgets/assets/127007861/e8d3ec9e-a8f9-4036-82c4-9795710e60f6)

同时询问amis，是否存在更便捷的方案
https://github.com/baidu/amis/issues/8258

**Comment by tujiajun** [comment]
amis2.9支持componentId的行记录字段赋值与crud列表赋值，基本可满足上述方案，并且询问amis得到的结果也与暂定的方案类似

**Comment by tujiajun** [comment]
上述方案存在以下问题：

1. 更新列表数据，修改各行的_display，需要覆盖数据，amis2.9目前不支持"dataMergeMode": "override"（等待升级）
2. amis2.9目前不支持字段通过${index}的方式给每行添加不同id（等待升级）
3. 行记录字段赋值要求字段必须有type，并且只支持部分type类型，例如static、swich等（tpl与mapping不支持，但我们内核中存在这两个类型，tpl可改成static，但mapping暂无解决方案）

**Comment by tujiajun** [comment]
![image](https://github.com/steedos/steedos-widgets/assets/127007861/987d1e15-768c-4519-b08a-46285655b1d0)
用于禁止勾选无权限的行记录

**Comment by tujiajun** [comment]
附件、图片字段不支持批量编辑；下拉框字段暂不支持，等待处理；目前只支持amis3.2
