### ISSUE TITLE
[Feature]: lookup 下拉模式底部增加新建按钮

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-widgets#470]
### Summary 摘要

目前picker列表模式有新建按钮，但是下拉模式没有。

![image](https://github.com/steedos/steedos-widgets/assets/6219465/9b36ca0a-c25a-45e7-901e-beff53351e50)

### Why should this be worked on? 此需求的应用场景？

方便快速新建相关表记录。

**Comment by Flyingliao** [comment]
重复任务：https://github.com/steedos/steedos-widgets/issues/298
