### ISSUE TITLE
[Task]: amis升级到3.2问题清单

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-widgets#473]
### SubTasks 子任务

- [x] 子表表头未显示记录数量（SteedosUI.getRef(api.body.$self.$scopeId)?.getComponentById(setDataToComponentId)?.setData({$count: payload.data.count})）
![image](https://github.com/steedos/steedos-widgets/assets/6219465/cce3beb9-abf9-4421-9e3c-59879929bdd1)

- [x] 子表附件加载异常【见上图】
- [x] 选项卡在左侧时没有垂直居中
![image](https://github.com/steedos/steedos-widgets/assets/6219465/9d395b74-3cc7-4b07-8bd3-449f44e79da4)

- [x] 顶部样式异常，蓝色缺失了右侧很大部分
![image](https://github.com/steedos/steedos-widgets/assets/6219465/b0f2913d-988e-447a-aa93-334609cc6450)

- [x] 列表右上角下拉框边距样式丢失
![image](https://github.com/steedos/steedos-widgets/assets/6219465/87597f17-5571-4e86-8edd-b185aa0529bc)

- [x] 新建编辑记录窗口以及只读的记录详细页面分组样式异常
![image](https://github.com/steedos/steedos-widgets/assets/6219465/87f1c502-27b3-4575-8032-4e9f45a6ab1a)

**Comment by tujiajun** [comment]
- [ ] 列表视图的批量删除按钮失效
![image](https://github.com/steedos/steedos-widgets/assets/127007861/07de5bcd-50a7-47a0-9341-fcc0f6bb6afe)

**Comment by tujiajun** [comment]
amis更改了getComponentByid,需要进行对应的改进
![image](https://github.com/steedos/steedos-widgets/assets/127007861/85c67121-ec4b-4b52-a0a8-fbcb7706606e)
