### ISSUE TITLE
[Feature]: lookup字段弹出的请选择改为请[选择+对象名]

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-widgets#474]
### Summary 摘要

amis 3.2已经支持给picker设置title了，之前2.9不支持
![image](https://github.com/steedos/steedos-widgets/assets/6219465/833c23a3-73b0-4af7-9839-84acf348d722)

### Why should this be worked on? 此需求的应用场景？

Lookup字段弹出窗口选择的时候不知道选择什么对象的记录

**Comment by Flyingliao** [comment]
amis的issue： 提供一个属性以便修改 Picker 列表选择器 弹窗左上角 的提示 [#7455](https://github.com/baidu/amis/issues/7455)
