### ISSUE TITLE
[Bug]: 列表视图组件中,无法获取到最新的父级数据

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-widgets#487]
### Description

![image](https://github.com/steedos/steedos-widgets/assets/6194462/ee08ec24-132f-4e0c-93cf-968fc3516806)

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos/steedos-widgets/assets/6194462/8bec5fed-c2c4-48b9-8622-91cda33193a1)

### Version 版本

1.x

**Comment by baozhoutao** [comment]
临时可以使用crud自带的外出service传递数据. service id 是: `service_listview_${objectName}`

**Comment by yinlianghui** [comment]
- 从列表视图组件往下一层一层加tpl显示数据链中的变量，第一层都能拿到，但是在rowClick事件中就是拿不到此变量。
![image](https://github.com/steedos/steedos-widgets/assets/6219465/1e6fedb6-90be-44ac-9219-e06254f8a4a8)

- 暂时不影响使用，可以先不处理
