### ISSUE TITLE
[Bug]:ObjectFrom根据id带出来的对象中有日期（如：2023-09-26 09:00），在amis设计器中手机预览报错

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-widgets#489]
### Description

ObjectFrom根据id带出来的对象中有日期（如：2023-09-26 09:00），在amis设计器中预览报错，
![image](https://github.com/steedos/steedos-platform/assets/129827462/b50ba227-80ad-4681-beea-e75438d16a49)
日期字段为空的时候，正常预览：
![image](https://github.com/steedos/steedos-platform/assets/129827462/0a3d695e-b209-4024-8263-629197ef89f1)
日期字段为不空的时候，预览报错：
![image](https://github.com/steedos/steedos-platform/assets/129827462/104d8b3f-61de-4722-8901-9a97011c9678)

### Steps To Reproduce 重现步骤

1、在一个编辑按钮设置点击事件为弹框
2、弹框内容为一个编辑的ObjectFrom对象表单
3、该对象有日期字段

### Version 版本

2.5.14

**Comment by yinlianghui** [comment]
- 这个问题只有设计器中才存在，前端界面是好的
- 问题已经修正，包老师改好了，但是需要更新builder.com

**Comment by Flyingliao** [comment]
已恢复正常了：
<img width="478" alt="image" src="https://github.com/steedos/steedos-widgets/assets/41402189/d7e62809-2034-4e2e-8912-d0113e121672">
