### ISSUE TITLE
[Feature]: 新建字段时字段类型选项应该允许搜索

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-widgets#501]
### Summary 摘要

- 直接用amis的下拉框搜索功能试下能不能实现，不用走服务端搜索
- 最好label和value都可以搜索，因为有时输入英文的value更方便
![image](https://github.com/steedos/steedos-widgets/assets/6219465/f5df0c0e-5c06-4ca7-836a-03c255af7f92)

### Why should this be worked on? 此需求的应用场景？

新建字段选字段类型不方便

**Comment by Flyingliao** [comment]
代码地址：https://github.com/steedos/steedos-platform/commit/4e437d67a130d8759be699a2cf9250f5670a64b4
