### ISSUE TITLE
[Bug]: 列表搜索时，如果在变更搜索条件后立即回车会触发重复请求

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-widgets#504]
### Description

- 列表快速搜索和顶部展开的筛选表单都有这个问题，如果搜索请求本身反应比较慢时问题会更明显
- 应该判断下正在请求期间禁止回车或其他方式触发重新请求直到请求完成后才允许触发新的搜索请求

### Steps To Reproduce 重现步骤

1. 进入任何一个对象的列表界面
2. 在快速搜索或顶部展开的筛选表单中输入过滤条件并立刻点击回车按钮
3. 可以看到network请求中触发了两次搜索

### Version 版本

2.5.20

**Comment by Flyingliao** [comment]
列表视图：
1、“筛选”按钮部分字段保留边改边搜，其它的字段启用失去焦点才搜索；
保留边改边搜的字段：['select', 'boolean', 'toggle', 'date', 'datetime', 'time', 'number', 'currency', 'lookup', 'master_detail']。
2、“搜索此列表”搜索框去掉边输边搜，启用失去焦点才搜索；
3、列表视图（对象表格）API设置缓存3s。

**Comment by yinlianghui** [comment]
此问题原因是之前为了兼容客户要求的快速搜索框和搜索表单两处同时使用的情况下，有时忘记点回车造成界面上过滤条件与实际请求结果不相符的问题，特意做了以下两次方案开发造成的：
- 过滤条件文本框中连输入搜索关键字边触发列表搜索请求【此方案会有本issue描述的性能问题】
- 为了解决性能问题把触发列表搜索请求的事件从搜索关键字值变更改为搜索框失去焦点【基本解决性能问题，但是在失去焦点的同一时刻点击列表链接进入记录详细页的话，还是会因为触发了多余的列表搜索请求造成性能问题】


最后换成的方案是：
快速搜索框和搜索表单两处，无论是从哪边触发的列表搜索请求，都同时把另一边的过滤条件同时带上。

**Comment by yinlianghui** [comment]
处理结果是解决了性能问题，同时兼容客户要求的快速搜索框和搜索表单两处同时使用的情况，且主列表搜索及lookup字段弹出的列表搜索规则统一修正了。
